name: 'Submodule Notify Parent'

on:
  push:
    branches: [main, test]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  notify:
    name: 'Submodule Notify Parent'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Github REST API Call for main
      if: github.ref == 'refs/heads/main'
      env:
        CI_TOKEN: ${{ secrets.CI_TOKEN }}
        PARENT_REPO: TimaGribanov/akfgfragments.com
        PARENT_BRANCH: main
        WORKFLOW_ID: 214395669
      run: |
        curl -fL --retry 3 -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ env.CI_TOKEN }}" https://api.github.com/repos/${{ env.PARENT_REPO }}/actions/workflows/${{ env.WORKFLOW_ID }}/dispatches -d '{"ref":"${{ env.PARENT_BRANCH }}"}'

    - name: Github REST API Call for test
      if: github.ref == 'refs/heads/test'
      env:
        CI_TOKEN: ${{ secrets.CI_TOKEN }}
        PARENT_REPO: TimaGribanov/akfgfragments.com
        PARENT_BRANCH: test
        WORKFLOW_ID: 214395669
      run: |
        curl -fL --retry 3 -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ env.CI_TOKEN }}" https://api.github.com/repos/${{ env.PARENT_REPO }}/actions/workflows/${{ env.WORKFLOW_ID }}/dispatches -d '{"ref":"${{ env.PARENT_BRANCH }}"}'
